apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-minikube
  labels:
    app: hello-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-minikube
  template:
    metadata:
      labels:
        app: hello-minikube
    spec:
      containers:
      - name: hello-minikube
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-minikube
spec:
  selector:
    app: hello-minikube
  type: NodePort
    ports:
      - port: 8080
        nodePort: 30036
        name: http
    selector:
      name: hello-minikube
